------------------------------------------
-- 1) LOCAL DE ENDEREÇO
------------------------------------------
CREATE TABLE STATES (
  STATE_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  STATE_NAME  VARCHAR2(255) NOT NULL
);

CREATE TABLE CITY (
  CITY_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME_CITY  VARCHAR2(255) NOT NULL,
  STATE_ID   NUMBER NOT NULL,
  CONSTRAINT FK_CITY_STATES
    FOREIGN KEY (STATE_ID) REFERENCES STATES(STATE_ID)
);

CREATE TABLE NEIGHBOURHOOD (
  NEIGH_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NEIGH_NAME  VARCHAR2(255) NOT NULL,
  CITY_ID     NUMBER NOT NULL,
  CONSTRAINT FK_NEIGH_CITY
    FOREIGN KEY (CITY_ID) REFERENCES CITY(CITY_ID)
);

CREATE TABLE ADDRESS_MANUFACTURER (
  ADDRESS_ID_MANUFACTURER NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMPLEMENT              VARCHAR2(255) NOT NULL,
  NUMBER_MANU             NUMBER(7)     NOT NULL,
  ADDRESS_DESCRIPTION     VARCHAR2(255) NOT NULL,
  CEP                     NUMBER(8)     NOT NULL,
  NEIGH_ID                NUMBER        NOT NULL,
  CONSTRAINT FK_ADDRMANU_NEIGH
    FOREIGN KEY (NEIGH_ID) REFERENCES NEIGHBOURHOOD(NEIGH_ID)
);

CREATE TABLE ADDRESS_STOCK (
  ADDRESS_ID_STOCK    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COMPLEMENT          VARCHAR2(255),
  NUMBER_STOCK        NUMBER(7)     NOT NULL,
  ADDRESS_DESCRIPTION VARCHAR2(255) NOT NULL,
  CEP                 NUMBER        NOT NULL,
  NEIGH_ID            NUMBER        NOT NULL,
  CONSTRAINT FK_ADDRSTOCK_NEIGH
    FOREIGN KEY (NEIGH_ID) REFERENCES NEIGHBOURHOOD(NEIGH_ID)
);

------------------------------------------
-- 2) LOCAL DE ESTOQUE
------------------------------------------

CREATE TABLE LOCATION_STOCK (
  LOCATION_ID_STOCK     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME_LOCATION   VARCHAR2(30)  NOT NULL,
  LOCATION_STOCK_NAME  VARCHAR2(100) NOT NULL,
  ADDRESS_ID_STOCK      NUMBER        NOT NULL,
  CONSTRAINT FK_LOCATION_ADDRSTOCK
    FOREIGN KEY (ADDRESS_ID_STOCK) REFERENCES ADDRESS_STOCK(ADDRESS_ID_STOCK),
  CONSTRAINT UQ_LOCATION_ADDRSTOCK UNIQUE (ADDRESS_ID_STOCK)
);

---------------------
-- 3) USUÁRIOS
---------------------

CREATE TABLE CONTACT_USER (
  CONTACT_USER_ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  EMAIL_USER        VARCHAR2(255) NOT NULL,
  PHONE_NUMBER_USER NUMBER        NOT NULL,
  CONSTRAINT UQ_CONTACT_USER_EMAIL UNIQUE (EMAIL_USER),
  CONSTRAINT UQ_CONTACT_USER_PHONE UNIQUE (PHONE_NUMBER_USER)
);


CREATE TABLE ROLE_USER (
  ROLE_USER_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  USER_ROLE    VARCHAR2(100) NOT NULL
);

CREATE TABLE PROFILE_USER (
  PROF_USER_ID  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  USER_PROFILE  VARCHAR2(50) 
);

CREATE TABLE USERS_SYS (
  USER_ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME_USER        VARCHAR2(150) NOT NULL,
  LOGIN            VARCHAR2(50)  NOT NULL,
  PASSWORD_USER    VARCHAR2(255) NOT NULL,
  ROLE_USER_ID     NUMBER NOT NULL,
  PROF_USER_ID     NUMBER NOT NULL,
  CONTACT_USER_ID  NUMBER NOT NULL,
  CONSTRAINT UQ_USERS_SYS_LOGIN UNIQUE (LOGIN),
  CONSTRAINT FK_USERS_ROLE     FOREIGN KEY (ROLE_USER_ID)     REFERENCES ROLE_USER(ROLE_USER_ID),
  CONSTRAINT FK_USERS_PROF     FOREIGN KEY (PROF_USER_ID)     REFERENCES PROFILE_USER(PROF_USER_ID),
  CONSTRAINT FK_USERS_CONTACT  FOREIGN KEY (CONTACT_USER_ID)  REFERENCES CONTACT_USER(CONTACT_USER_ID)
);

---------------------
-- 4) FABRICANTES
---------------------

CREATE TABLE CONTACT_MANUFACTURER (
  CONTACT_MANU_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  EMAIL_MANU         VARCHAR2(255) NOT NULL,
  PHONE_NUMBER_MANU  NUMBER        NOT NULL,
  CONSTRAINT UQ_CONTACT_MANU_EMAIL UNIQUE (EMAIL_MANU),
  CONSTRAINT UQ_CONTACT_MANU_PHONE UNIQUE (PHONE_NUMBER_MANU)
);

CREATE TABLE MANUFACTURER (
  MANUFAC_ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME_MANU               VARCHAR2(255) NOT NULL,
  CNPJ                    NUMBER(14)    NOT NULL,
  ADDRESS_ID_MANUFACTURER NUMBER        NOT NULL,
  CONTACT_MANU_ID         NUMBER        NOT NULL,
  CONSTRAINT UQ_MANUFACTURER_CNPJ UNIQUE (CNPJ),
  CONSTRAINT FK_MANU_ADDRESSMANU
    FOREIGN KEY (ADDRESS_ID_MANUFACTURER) REFERENCES ADDRESS_MANUFACTURER(ADDRESS_ID_MANUFACTURER),
  CONSTRAINT FK_MANU_CONTACT
    FOREIGN KEY (CONTACT_MANU_ID) REFERENCES CONTACT_MANUFACTURER(CONTACT_MANU_ID)
);

---------------------
-- 5) CATÁLOGOS
---------------------

CREATE TABLE ACTIVE_INGREDIENT (
  ACT_INGRE_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ACT_INGREDIENT  VARCHAR2(200) NOT NULL
);

CREATE TABLE PHARMACEUTICAL_FORM (
  PHARM_FORM_ID  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  PHARMA_FORM    VARCHAR2(100) NOT NULL
);

CREATE TABLE UNIT_MEASURE (
  UNIT_MEA_ID             NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  UNIT_MEASURE_MEDICINE   VARCHAR2(20) NOT NULL
);

CREATE TABLE CATEGORY_MEDICINE (
  CATEGORY_MED_ID  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CATEGORY         VARCHAR2(255) NOT NULL
);

---------------------
-- 6) MEDICINES 
---------------------

CREATE TABLE MEDICINES (
  MEDICINE_ID     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME_MEDICATION VARCHAR2(255) NOT NULL,
  STATUS_MED      VARCHAR2(20)  NOT NULL,
  CATEGORY_MED_ID NUMBER NOT NULL,
  UNIT_MEA_ID     NUMBER NOT NULL,
  CONSTRAINT FK_MED_CATEGORY  FOREIGN KEY (CATEGORY_MED_ID) REFERENCES CATEGORY_MEDICINE(CATEGORY_MED_ID),
  CONSTRAINT FK_MED_UNIT      FOREIGN KEY (UNIT_MEA_ID)     REFERENCES UNIT_MEASURE(UNIT_MEA_ID)
);

CREATE TABLE MEDICINE_ACTIVE_INGR (
  MED_ACTIVE_INGR_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  MEDICINE_ID  NUMBER NOT NULL,
  ACT_INGRE_ID NUMBER NOT NULL,
  CONSTRAINT FK_MAI_MEDICINE  FOREIGN KEY (MEDICINE_ID)  REFERENCES MEDICINES(MEDICINE_ID),
  CONSTRAINT FK_MAI_INGRED    FOREIGN KEY (ACT_INGRE_ID) REFERENCES ACTIVE_INGREDIENT(ACT_INGRE_ID)
);

CREATE TABLE MEDICINE_PHARM_FORM (
  MED_PHARM_FORM_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  MEDICINE_ID   NUMBER NOT NULL,
  PHARM_FORM_ID NUMBER NOT NULL,
  CONSTRAINT FK_MPF_MEDICINE  FOREIGN KEY (MEDICINE_ID)   REFERENCES MEDICINES(MEDICINE_ID),
  CONSTRAINT FK_MPF_PHARM     FOREIGN KEY (PHARM_FORM_ID) REFERENCES PHARMACEUTICAL_FORM(PHARM_FORM_ID)
);

------------------------------------------
-- 7) LOTES
------------------------------------------

CREATE TABLE BATCH_MEDICINE (
  BATCH_ID  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  BATCH_NUMBER       VARCHAR2(255) NOT NULL,
  CURRENT_QUANTITY   NUMBER        NOT NULL,
  MANUFACTURING_DATE DATE          NOT NULL,
  EXPIRATION_DATE    DATE          NOT NULL,
  MANUFAC_ID         NUMBER        NOT NULL,
  CONSTRAINT FK_BATCH_MANUFACTURER
    FOREIGN KEY (MANUFAC_ID) REFERENCES MANUFACTURER(MANUFAC_ID)
);

CREATE TABLE MOVEMENT_TYPE (
  MOVEMENT_TYPE_ID  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TYPE_NAME         VARCHAR2(30) NOT NULL
);

CREATE TABLE STOCK (
  STOCK_ID           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  QUANTITY           NUMBER(6) NOT NULL,
  BATCH_ID  NUMBER    NOT NULL,
  MEDICINE_ID        NUMBER    NOT NULL,
  LOCATION_ID_STOCK  NUMBER    NOT NULL,
  CONSTRAINT FK_STOCK_BATCH    FOREIGN KEY (BATCH_ID) REFERENCES BATCH_MEDICINE(BATCH_ID),
  CONSTRAINT FK_STOCK_MED      FOREIGN KEY (MEDICINE_ID)       REFERENCES MEDICINES(MEDICINE_ID),
  CONSTRAINT FK_STOCK_LOCATION FOREIGN KEY (LOCATION_ID_STOCK) REFERENCES LOCATION_STOCK(LOCATION_ID_STOCK)
);

---------------------
-- 8) DISPENSAÇÃO
---------------------

CREATE TABLE MEDICINE_DISPENSE (
  DISPENSATION_ID     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  DATE_DISPENSATION   DATE          NOT NULL,
  QUANTITY_DISPENSED  NUMBER(6)     NOT NULL,
  DESTINATION         VARCHAR2(255) NOT NULL,
  OBSERVATION         VARCHAR2(255),
  USER_ID             NUMBER        NOT NULL,
  CONSTRAINT FK_DISP_USER       FOREIGN KEY (USER_ID)          REFERENCES USERS_SYS(USER_ID)
);

------------------------------------------------
--  9) NOVA TABELA: STOCK_MOVEMENT 
------------------------------------------------
CREATE TABLE STOCK_MOVEMENT (
  STOCK_MOVEMENT_ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  QUANTITY_DISPENSED  NUMBER(6)    NOT NULL, 
  DATE_MOVIMENT DATE NOT NULL,
  MOVEMENT_TYPE_ID    NUMBER,  
  STOCK_ID            NUMBER       NOT NULL,  
  DISPENSATION_ID     NUMBER       NOT NULL, 
  USER_ID             NUMBER,                 
  CONSTRAINT FK_STKMOV_MOVTYPE   FOREIGN KEY (MOVEMENT_TYPE_ID) REFERENCES MOVEMENT_TYPE(MOVEMENT_TYPE_ID),
  CONSTRAINT FK_STKMOV_STOCK     FOREIGN KEY (STOCK_ID)         REFERENCES STOCK(STOCK_ID),
  CONSTRAINT FK_STKMOV_DISPENSE  FOREIGN KEY (DISPENSATION_ID)  REFERENCES MEDICINE_DISPENSE(DISPENSATION_ID),
  CONSTRAINT FK_STKMOV_USER      FOREIGN KEY (USER_ID)          REFERENCES USERS_SYS(USER_ID)

);

---------------------
-- INSERT STATES
---------------------

INSERT INTO STATES (STATE_NAME) VALUES ('São Paulo');
INSERT INTO STATES (STATE_NAME) VALUES ('Rio de Janeiro');
INSERT INTO STATES (STATE_NAME) VALUES ('Minas Gerais');
INSERT INTO STATES (STATE_NAME) VALUES ('Rio Grande do Sul');
INSERT INTO STATES (STATE_NAME) VALUES ('Paraná');
INSERT INTO STATES (STATE_NAME) VALUES ('Santa Catarina');
INSERT INTO STATES (STATE_NAME) VALUES ('Bahia');
INSERT INTO STATES (STATE_NAME) VALUES ('Pernambuco');
INSERT INTO STATES (STATE_NAME) VALUES ('Ceará');
INSERT INTO STATES (STATE_NAME) VALUES ('Distrito Federal');
INSERT INTO STATES (STATE_NAME) VALUES ('Goiás');
INSERT INTO STATES (STATE_NAME) VALUES ('Espírito Santo');
INSERT INTO STATES (STATE_NAME) VALUES ('Mato Grosso');
INSERT INTO STATES (STATE_NAME) VALUES ('Mato Grosso do Sul');
INSERT INTO STATES (STATE_NAME) VALUES ('Pará');

---------------------
-- INSERT CITY
---------------------
INSERT INTO CITY (NAME_CITY, STATE_ID) VALUES ('São Paulo', 1);
INSERT INTO CITY (NAME_CITY, STATE_ID) VALUES ('Campinas', 1);
INSERT INTO CITY (NAME_CITY, STATE_ID) VALUES ('Santos', 1);
INSERT INTO CITY (NAME_CITY, STATE_ID) VALUES ('Rio de Janeiro', 2);
INSERT INTO CITY (NAME_CITY, STATE_ID) VALUES ('Niterói', 2);
INSERT INTO CITY (NAME_CITY, STATE_ID) VALUES ('Belo Horizonte', 3);
INSERT INTO CITY (NAME_CITY, STATE_ID) VALUES ('Uberlândia', 3);
INSERT INTO CITY (NAME_CITY, STATE_ID) VALUES ('Porto Alegre', 4);
INSERT INTO CITY (NAME_CITY, STATE_ID) VALUES ('Caxias do Sul', 4);
INSERT INTO CITY (NAME_CITY, STATE_ID) VALUES ('Curitiba', 5);
INSERT INTO CITY (NAME_CITY, STATE_ID) VALUES ('Londrina', 5);
INSERT INTO CITY (NAME_CITY, STATE_ID) VALUES ('Florianópolis', 6);
INSERT INTO CITY (NAME_CITY, STATE_ID) VALUES ('Joinville', 6);
INSERT INTO CITY (NAME_CITY, STATE_ID) VALUES ('Salvador', 7);
INSERT INTO CITY (NAME_CITY, STATE_ID) VALUES ('Recife', 8);

------------------------------------------
-- INSERT NEIGHBOURHOOD
------------------------------------------
INSERT INTO NEIGHBOURHOOD (NEIGH_NAME, CITY_ID) VALUES ('Centro', 1);
INSERT INTO NEIGHBOURHOOD (NEIGH_NAME, CITY_ID) VALUES ('Pinheiros', 1);
INSERT INTO NEIGHBOURHOOD (NEIGH_NAME, CITY_ID) VALUES ('Moema', 1);
INSERT INTO NEIGHBOURHOOD (NEIGH_NAME, CITY_ID) VALUES ('Copacabana', 4);
INSERT INTO NEIGHBOURHOOD (NEIGH_NAME, CITY_ID) VALUES ('Ipanema', 4);
INSERT INTO NEIGHBOURHOOD (NEIGH_NAME, CITY_ID) VALUES ('Savassi', 6);
INSERT INTO NEIGHBOURHOOD (NEIGH_NAME, CITY_ID) VALUES ('Pampulha', 6);
INSERT INTO NEIGHBOURHOOD (NEIGH_NAME, CITY_ID) VALUES ('Moinhos de Vento', 8);
INSERT INTO NEIGHBOURHOOD (NEIGH_NAME, CITY_ID) VALUES ('Petrópolis', 8);
INSERT INTO NEIGHBOURHOOD (NEIGH_NAME, CITY_ID) VALUES ('Batel', 10);
INSERT INTO NEIGHBOURHOOD (NEIGH_NAME, CITY_ID) VALUES ('Gleba Palhano', 11);
INSERT INTO NEIGHBOURHOOD (NEIGH_NAME, CITY_ID) VALUES ('Centro', 12);
INSERT INTO NEIGHBOURHOOD (NEIGH_NAME, CITY_ID) VALUES ('América', 13);
INSERT INTO NEIGHBOURHOOD (NEIGH_NAME, CITY_ID) VALUES ('Barra', 14);
INSERT INTO NEIGHBOURHOOD (NEIGH_NAME, CITY_ID) VALUES ('Boa Viagem', 15);

------------------------------------------
-- INSERT ADDRESS_MANUFACTURER
------------------------------------------
INSERT INTO ADDRESS_MANUFACTURER (COMPLEMENT, NUMBER_MANU, ADDRESS_DESCRIPTION, CEP, NEIGH_ID) VALUES ('Bloco A', 101, 'Rua Industrial 1', 10000137, 1);
INSERT INTO ADDRESS_MANUFACTURER (COMPLEMENT, NUMBER_MANU, ADDRESS_DESCRIPTION, CEP, NEIGH_ID) VALUES ('Bloco B', 102, 'Rua Industrial 2', 10000274, 2);
INSERT INTO ADDRESS_MANUFACTURER (COMPLEMENT, NUMBER_MANU, ADDRESS_DESCRIPTION, CEP, NEIGH_ID) VALUES ('Bloco C', 103, 'Rua Industrial 3', 10000411, 3);
INSERT INTO ADDRESS_MANUFACTURER (COMPLEMENT, NUMBER_MANU, ADDRESS_DESCRIPTION, CEP, NEIGH_ID) VALUES ('Bloco D', 104, 'Rua Industrial 4', 10000548, 4);
INSERT INTO ADDRESS_MANUFACTURER (COMPLEMENT, NUMBER_MANU, ADDRESS_DESCRIPTION, CEP, NEIGH_ID) VALUES ('Bloco E', 105, 'Rua Industrial 5', 10000685, 5);
INSERT INTO ADDRESS_MANUFACTURER (COMPLEMENT, NUMBER_MANU, ADDRESS_DESCRIPTION, CEP, NEIGH_ID) VALUES ('Bloco A', 106, 'Rua Industrial 6', 10000822, 6);
INSERT INTO ADDRESS_MANUFACTURER (COMPLEMENT, NUMBER_MANU, ADDRESS_DESCRIPTION, CEP, NEIGH_ID) VALUES ('Bloco B', 107, 'Rua Industrial 7', 10000959, 7);
INSERT INTO ADDRESS_MANUFACTURER (COMPLEMENT, NUMBER_MANU, ADDRESS_DESCRIPTION, CEP, NEIGH_ID) VALUES ('Bloco C', 108, 'Rua Industrial 8', 10001096, 8);
INSERT INTO ADDRESS_MANUFACTURER (COMPLEMENT, NUMBER_MANU, ADDRESS_DESCRIPTION, CEP, NEIGH_ID) VALUES ('Bloco D', 109, 'Rua Industrial 9', 10001233, 9);
INSERT INTO ADDRESS_MANUFACTURER (COMPLEMENT, NUMBER_MANU, ADDRESS_DESCRIPTION, CEP, NEIGH_ID) VALUES ('Bloco E', 110, 'Rua Industrial 10', 10001370, 10);
INSERT INTO ADDRESS_MANUFACTURER (COMPLEMENT, NUMBER_MANU, ADDRESS_DESCRIPTION, CEP, NEIGH_ID) VALUES ('Bloco A', 111, 'Rua Industrial 11', 10001507, 11);
INSERT INTO ADDRESS_MANUFACTURER (COMPLEMENT, NUMBER_MANU, ADDRESS_DESCRIPTION, CEP, NEIGH_ID) VALUES ('Bloco B', 112, 'Rua Industrial 12', 10001644, 12);
INSERT INTO ADDRESS_MANUFACTURER (COMPLEMENT, NUMBER_MANU, ADDRESS_DESCRIPTION, CEP, NEIGH_ID) VALUES ('Bloco C', 113, 'Rua Industrial 13', 10001781, 13);
INSERT INTO ADDRESS_MANUFACTURER (COMPLEMENT, NUMBER_MANU, ADDRESS_DESCRIPTION, CEP, NEIGH_ID) VALUES ('Bloco D', 114, 'Rua Industrial 14', 10001918, 14);
INSERT INTO ADDRESS_MANUFACTURER (COMPLEMENT, NUMBER_MANU, ADDRESS_DESCRIPTION, CEP, NEIGH_ID) VALUES ('Bloco E', 115, 'Rua Industrial 15', 10002055, 15);

---------------------
-- ADDRESS_STOCK
---------------------
INSERT INTO ADDRESS_STOCK (COMPLEMENT, NUMBER_STOCK, ADDRESS_DESCRIPTION, CEP, NEIGH_ID) VALUES ('Depósito', 201, 'Av. Logística 1', 20000149, 1);
INSERT INTO ADDRESS_STOCK (COMPLEMENT, NUMBER_STOCK, ADDRESS_DESCRIPTION, CEP, NEIGH_ID) VALUES ('Depósito', 202, 'Av. Logística 2', 20000298, 2);
INSERT INTO ADDRESS_STOCK (COMPLEMENT, NUMBER_STOCK, ADDRESS_DESCRIPTION, CEP, NEIGH_ID) VALUES ('Galpão 3', 203, 'Av. Logística 3', 20000447, 3);
INSERT INTO ADDRESS_STOCK (COMPLEMENT, NUMBER_STOCK, ADDRESS_DESCRIPTION, CEP, NEIGH_ID) VALUES ('Depósito', 204, 'Av. Logística 4', 20000596, 4);
INSERT INTO ADDRESS_STOCK (COMPLEMENT, NUMBER_STOCK, ADDRESS_DESCRIPTION, CEP, NEIGH_ID) VALUES ('Depósito', 205, 'Av. Logística 5', 20000745, 5);
INSERT INTO ADDRESS_STOCK (COMPLEMENT, NUMBER_STOCK, ADDRESS_DESCRIPTION, CEP, NEIGH_ID) VALUES ('Galpão 6', 206, 'Av. Logística 6', 20000894, 6);
INSERT INTO ADDRESS_STOCK (COMPLEMENT, NUMBER_STOCK, ADDRESS_DESCRIPTION, CEP, NEIGH_ID) VALUES ('Depósito', 207, 'Av. Logística 7', 20001043, 7);
INSERT INTO ADDRESS_STOCK (COMPLEMENT, NUMBER_STOCK, ADDRESS_DESCRIPTION, CEP, NEIGH_ID) VALUES ('Depósito', 208, 'Av. Logística 8', 20001192, 8);
INSERT INTO ADDRESS_STOCK (COMPLEMENT, NUMBER_STOCK, ADDRESS_DESCRIPTION, CEP, NEIGH_ID) VALUES ('Galpão 9', 209, 'Av. Logística 9', 20001341, 9);
INSERT INTO ADDRESS_STOCK (COMPLEMENT, NUMBER_STOCK, ADDRESS_DESCRIPTION, CEP, NEIGH_ID) VALUES ('Depósito', 210, 'Av. Logística 10', 20001490, 10);
INSERT INTO ADDRESS_STOCK (COMPLEMENT, NUMBER_STOCK, ADDRESS_DESCRIPTION, CEP, NEIGH_ID) VALUES ('Depósito', 211, 'Av. Logística 11', 20001639, 11);
INSERT INTO ADDRESS_STOCK (COMPLEMENT, NUMBER_STOCK, ADDRESS_DESCRIPTION, CEP, NEIGH_ID) VALUES ('Galpão 12', 212, 'Av. Logística 12', 20001788, 12);
INSERT INTO ADDRESS_STOCK (COMPLEMENT, NUMBER_STOCK, ADDRESS_DESCRIPTION, CEP, NEIGH_ID) VALUES ('Depósito', 213, 'Av. Logística 13', 20001937, 13);
INSERT INTO ADDRESS_STOCK (COMPLEMENT, NUMBER_STOCK, ADDRESS_DESCRIPTION, CEP, NEIGH_ID) VALUES ('Depósito', 214, 'Av. Logística 14', 20002086, 14);
INSERT INTO ADDRESS_STOCK (COMPLEMENT, NUMBER_STOCK, ADDRESS_DESCRIPTION, CEP, NEIGH_ID) VALUES ('Galpão 15', 215, 'Av. Logística 15', 20002235, 15);

------------------------------------------
-- INSERT LOCATION_STOCK
------------------------------------------
INSERT INTO LOCATION_STOCK (NAME_LOCATION, LOCATION_STOCK_NAME, ADDRESS_ID_STOCK) VALUES ('Almox 1', 'Almoxarifado principal 1', 1);
INSERT INTO LOCATION_STOCK (NAME_LOCATION, LOCATION_STOCK_NAME, ADDRESS_ID_STOCK) VALUES ('Almox 2', 'Almoxarifado principal 2', 2);
INSERT INTO LOCATION_STOCK (NAME_LOCATION, LOCATION_STOCK_NAME, ADDRESS_ID_STOCK) VALUES ('Almox 3', 'Almoxarifado principal 3', 3);
INSERT INTO LOCATION_STOCK (NAME_LOCATION, LOCATION_STOCK_NAME, ADDRESS_ID_STOCK) VALUES ('Almox 4', 'Almoxarifado principal 4', 4);
INSERT INTO LOCATION_STOCK (NAME_LOCATION, LOCATION_STOCK_NAME, ADDRESS_ID_STOCK) VALUES ('Almox 5', 'Almoxarifado principal 5', 5);
INSERT INTO LOCATION_STOCK (NAME_LOCATION, LOCATION_STOCK_NAME, ADDRESS_ID_STOCK) VALUES ('Almox 6', 'Almoxarifado principal 6', 6);
INSERT INTO LOCATION_STOCK (NAME_LOCATION, LOCATION_STOCK_NAME, ADDRESS_ID_STOCK) VALUES ('Almox 7', 'Almoxarifado principal 7', 7);
INSERT INTO LOCATION_STOCK (NAME_LOCATION, LOCATION_STOCK_NAME, ADDRESS_ID_STOCK) VALUES ('Almox 8', 'Almoxarifado principal 8', 8);
INSERT INTO LOCATION_STOCK (NAME_LOCATION, LOCATION_STOCK_NAME, ADDRESS_ID_STOCK) VALUES ('Almox 9', 'Almoxarifado principal 9', 9);
INSERT INTO LOCATION_STOCK (NAME_LOCATION, LOCATION_STOCK_NAME, ADDRESS_ID_STOCK) VALUES ('Almox 10', 'Almoxarifado principal 10', 10);
INSERT INTO LOCATION_STOCK (NAME_LOCATION, LOCATION_STOCK_NAME, ADDRESS_ID_STOCK) VALUES ('Almox 11', 'Almoxarifado principal 11', 11);
INSERT INTO LOCATION_STOCK (NAME_LOCATION, LOCATION_STOCK_NAME, ADDRESS_ID_STOCK) VALUES ('Almox 12', 'Almoxarifado principal 12', 12);
INSERT INTO LOCATION_STOCK (NAME_LOCATION, LOCATION_STOCK_NAME, ADDRESS_ID_STOCK) VALUES ('Almox 13', 'Almoxarifado principal 13', 13);
INSERT INTO LOCATION_STOCK (NAME_LOCATION, LOCATION_STOCK_NAME, ADDRESS_ID_STOCK) VALUES ('Almox 14', 'Almoxarifado principal 14', 14);
INSERT INTO LOCATION_STOCK (NAME_LOCATION, LOCATION_STOCK_NAME, ADDRESS_ID_STOCK) VALUES ('Almox 15', 'Almoxarifado principal 15', 15);

------------------------------------------
-- INSERT CONTACT_USER
------------------------------------------
INSERT INTO CONTACT_USER (EMAIL_USER, PHONE_NUMBER_USER) VALUES ('usuario1@medsave.com', 5501199990001);
INSERT INTO CONTACT_USER (EMAIL_USER, PHONE_NUMBER_USER) VALUES ('usuario2@medsave.com', 5501199990002);
INSERT INTO CONTACT_USER (EMAIL_USER, PHONE_NUMBER_USER) VALUES ('usuario3@medsave.com', 5501199990003);
INSERT INTO CONTACT_USER (EMAIL_USER, PHONE_NUMBER_USER) VALUES ('usuario4@medsave.com', 5501199990004);
INSERT INTO CONTACT_USER (EMAIL_USER, PHONE_NUMBER_USER) VALUES ('usuario5@medsave.com', 5501199990005);
INSERT INTO CONTACT_USER (EMAIL_USER, PHONE_NUMBER_USER) VALUES ('usuario6@medsave.com', 5501199990006);
INSERT INTO CONTACT_USER (EMAIL_USER, PHONE_NUMBER_USER) VALUES ('usuario7@medsave.com', 5501199990007);
INSERT INTO CONTACT_USER (EMAIL_USER, PHONE_NUMBER_USER) VALUES ('usuario8@medsave.com', 5501199990008);
INSERT INTO CONTACT_USER (EMAIL_USER, PHONE_NUMBER_USER) VALUES ('usuario9@medsave.com', 5501199990009);
INSERT INTO CONTACT_USER (EMAIL_USER, PHONE_NUMBER_USER) VALUES ('usuario10@medsave.com', 5501199990010);
INSERT INTO CONTACT_USER (EMAIL_USER, PHONE_NUMBER_USER) VALUES ('usuario11@medsave.com', 5501199990011);
INSERT INTO CONTACT_USER (EMAIL_USER, PHONE_NUMBER_USER) VALUES ('usuario12@medsave.com', 5501199990012);
INSERT INTO CONTACT_USER (EMAIL_USER, PHONE_NUMBER_USER) VALUES ('usuario13@medsave.com', 5501199990013);
INSERT INTO CONTACT_USER (EMAIL_USER, PHONE_NUMBER_USER) VALUES ('usuario14@medsave.com', 5501199990014);
INSERT INTO CONTACT_USER (EMAIL_USER, PHONE_NUMBER_USER) VALUES ('usuario15@medsave.com', 5501199990015);

---------------------
-- INSERT ROLE_USER
---------------------
INSERT INTO ROLE_USER (USER_ROLE) VALUES ('ADMIN');
INSERT INTO ROLE_USER (USER_ROLE) VALUES ('FARMACÊUTICO');
INSERT INTO ROLE_USER (USER_ROLE) VALUES ('TÉCNICO_FARMA');
INSERT INTO ROLE_USER (USER_ROLE) VALUES ('ENFERMEIRO');
INSERT INTO ROLE_USER (USER_ROLE) VALUES ('MÉDICO');
INSERT INTO ROLE_USER (USER_ROLE) VALUES ('AUDITOR');
INSERT INTO ROLE_USER (USER_ROLE) VALUES ('COMPRAS');
INSERT INTO ROLE_USER (USER_ROLE) VALUES ('ALMOXARIFE');
INSERT INTO ROLE_USER (USER_ROLE) VALUES ('GESTOR');
INSERT INTO ROLE_USER (USER_ROLE) VALUES ('OPERADOR');
INSERT INTO ROLE_USER (USER_ROLE) VALUES ('SUPERVISOR');
INSERT INTO ROLE_USER (USER_ROLE) VALUES ('QUALIDADE');
INSERT INTO ROLE_USER (USER_ROLE) VALUES ('LOGÍSTICA');
INSERT INTO ROLE_USER (USER_ROLE) VALUES ('INVENTÁRIO');
INSERT INTO ROLE_USER (USER_ROLE) VALUES ('VISUALIZADOR');

------------------------------------------
-- INSERT PROFILE_USER
------------------------------------------
INSERT INTO PROFILE_USER (USER_PROFILE) VALUES ('Padrão');
INSERT INTO PROFILE_USER (USER_PROFILE) VALUES ('Avançado');
INSERT INTO PROFILE_USER (USER_PROFILE) VALUES ('Restrito');
INSERT INTO PROFILE_USER (USER_PROFILE) VALUES ('Auditoria');
INSERT INTO PROFILE_USER (USER_PROFILE) VALUES ('Compras');
INSERT INTO PROFILE_USER (USER_PROFILE) VALUES ('Farmácia');
INSERT INTO PROFILE_USER (USER_PROFILE) VALUES ('Enfermaria');
INSERT INTO PROFILE_USER (USER_PROFILE) VALUES ('Médico');
INSERT INTO PROFILE_USER (USER_PROFILE) VALUES ('Gestão');
INSERT INTO PROFILE_USER (USER_PROFILE) VALUES ('Operacional');
INSERT INTO PROFILE_USER (USER_PROFILE) VALUES ('Supervisor');
INSERT INTO PROFILE_USER (USER_PROFILE) VALUES ('Qualidade');
INSERT INTO PROFILE_USER (USER_PROFILE) VALUES ('Logística');
INSERT INTO PROFILE_USER (USER_PROFILE) VALUES ('Inventário');
INSERT INTO PROFILE_USER (USER_PROFILE) VALUES ('Somente Leitura');

---------------------
-- INSERT USERS_SYS
---------------------
INSERT INTO USERS_SYS (NAME_USER, LOGIN, PASSWORD_USER, ROLE_USER_ID, PROF_USER_ID, CONTACT_USER_ID) VALUES ('Usuário 1', 'user01', 'hash_senha_01', 1, 1, 1);
INSERT INTO USERS_SYS (NAME_USER, LOGIN, PASSWORD_USER, ROLE_USER_ID, PROF_USER_ID, CONTACT_USER_ID) VALUES ('Usuário 2', 'user02', 'hash_senha_02', 2, 2, 2);
INSERT INTO USERS_SYS (NAME_USER, LOGIN, PASSWORD_USER, ROLE_USER_ID, PROF_USER_ID, CONTACT_USER_ID) VALUES ('Usuário 3', 'user03', 'hash_senha_03', 3, 3, 3);
INSERT INTO USERS_SYS (NAME_USER, LOGIN, PASSWORD_USER, ROLE_USER_ID, PROF_USER_ID, CONTACT_USER_ID) VALUES ('Usuário 4', 'user04', 'hash_senha_04', 4, 4, 4);
INSERT INTO USERS_SYS (NAME_USER, LOGIN, PASSWORD_USER, ROLE_USER_ID, PROF_USER_ID, CONTACT_USER_ID) VALUES ('Usuário 5', 'user05', 'hash_senha_05', 5, 5, 5);
INSERT INTO USERS_SYS (NAME_USER, LOGIN, PASSWORD_USER, ROLE_USER_ID, PROF_USER_ID, CONTACT_USER_ID) VALUES ('Usuário 6', 'user06', 'hash_senha_06', 6, 6, 6);
INSERT INTO USERS_SYS (NAME_USER, LOGIN, PASSWORD_USER, ROLE_USER_ID, PROF_USER_ID, CONTACT_USER_ID) VALUES ('Usuário 7', 'user07', 'hash_senha_07', 7, 7, 7);
INSERT INTO USERS_SYS (NAME_USER, LOGIN, PASSWORD_USER, ROLE_USER_ID, PROF_USER_ID, CONTACT_USER_ID) VALUES ('Usuário 8', 'user08', 'hash_senha_08', 8, 8, 8);
INSERT INTO USERS_SYS (NAME_USER, LOGIN, PASSWORD_USER, ROLE_USER_ID, PROF_USER_ID, CONTACT_USER_ID) VALUES ('Usuário 9', 'user09', 'hash_senha_09', 9, 9, 9);
INSERT INTO USERS_SYS (NAME_USER, LOGIN, PASSWORD_USER, ROLE_USER_ID, PROF_USER_ID, CONTACT_USER_ID) VALUES ('Usuário 10', 'user10', 'hash_senha_10', 10, 10, 10);
INSERT INTO USERS_SYS (NAME_USER, LOGIN, PASSWORD_USER, ROLE_USER_ID, PROF_USER_ID, CONTACT_USER_ID) VALUES ('Usuário 11', 'user11', 'hash_senha_11', 11, 11, 11);
INSERT INTO USERS_SYS (NAME_USER, LOGIN, PASSWORD_USER, ROLE_USER_ID, PROF_USER_ID, CONTACT_USER_ID) VALUES ('Usuário 12', 'user12', 'hash_senha_12', 12, 12, 12);
INSERT INTO USERS_SYS (NAME_USER, LOGIN, PASSWORD_USER, ROLE_USER_ID, PROF_USER_ID, CONTACT_USER_ID) VALUES ('Usuário 13', 'user13', 'hash_senha_13', 13, 13, 13);
INSERT INTO USERS_SYS (NAME_USER, LOGIN, PASSWORD_USER, ROLE_USER_ID, PROF_USER_ID, CONTACT_USER_ID) VALUES ('Usuário 14', 'user14', 'hash_senha_14', 14, 14, 14);
INSERT INTO USERS_SYS (NAME_USER, LOGIN, PASSWORD_USER, ROLE_USER_ID, PROF_USER_ID, CONTACT_USER_ID) VALUES ('Usuário 15', 'user15', 'hash_senha_15', 15, 15, 15);

------------------------------------------
-- INSERT CONTACT_MANUFACTURER
------------------------------------------
INSERT INTO CONTACT_MANUFACTURER (EMAIL_MANU, PHONE_NUMBER_MANU) VALUES ('contato1@fabricante.com', 5501123456001);
INSERT INTO CONTACT_MANUFACTURER (EMAIL_MANU, PHONE_NUMBER_MANU) VALUES ('contato2@fabricante.com', 5501123456002);
INSERT INTO CONTACT_MANUFACTURER (EMAIL_MANU, PHONE_NUMBER_MANU) VALUES ('contato3@fabricante.com', 5501123456003);
INSERT INTO CONTACT_MANUFACTURER (EMAIL_MANU, PHONE_NUMBER_MANU) VALUES ('contato4@fabricante.com', 5501123456004);
INSERT INTO CONTACT_MANUFACTURER (EMAIL_MANU, PHONE_NUMBER_MANU) VALUES ('contato5@fabricante.com', 5501123456005);
INSERT INTO CONTACT_MANUFACTURER (EMAIL_MANU, PHONE_NUMBER_MANU) VALUES ('contato6@fabricante.com', 5501123456006);
INSERT INTO CONTACT_MANUFACTURER (EMAIL_MANU, PHONE_NUMBER_MANU) VALUES ('contato7@fabricante.com', 5501123456007);
INSERT INTO CONTACT_MANUFACTURER (EMAIL_MANU, PHONE_NUMBER_MANU) VALUES ('contato8@fabricante.com', 5501123456008);
INSERT INTO CONTACT_MANUFACTURER (EMAIL_MANU, PHONE_NUMBER_MANU) VALUES ('contato9@fabricante.com', 5501123456009);
INSERT INTO CONTACT_MANUFACTURER (EMAIL_MANU, PHONE_NUMBER_MANU) VALUES ('contato10@fabricante.com', 5501123456010);
INSERT INTO CONTACT_MANUFACTURER (EMAIL_MANU, PHONE_NUMBER_MANU) VALUES ('contato11@fabricante.com', 5501123456011);
INSERT INTO CONTACT_MANUFACTURER (EMAIL_MANU, PHONE_NUMBER_MANU) VALUES ('contato12@fabricante.com', 5501123456012);
INSERT INTO CONTACT_MANUFACTURER (EMAIL_MANU, PHONE_NUMBER_MANU) VALUES ('contato13@fabricante.com', 5501123456013);
INSERT INTO CONTACT_MANUFACTURER (EMAIL_MANU, PHONE_NUMBER_MANU) VALUES ('contato14@fabricante.com', 5501123456014);
INSERT INTO CONTACT_MANUFACTURER (EMAIL_MANU, PHONE_NUMBER_MANU) VALUES ('contato15@fabricante.com', 5501123456015);

------------------------------------------
-- INSERT MANUFACTURER
------------------------------------------
INSERT INTO MANUFACTURER (NAME_MANU, CNPJ, ADDRESS_ID_MANUFACTURER, CONTACT_MANU_ID) VALUES ('Fabricante 1 S.A.', 10000000000001, 1, 1);
INSERT INTO MANUFACTURER (NAME_MANU, CNPJ, ADDRESS_ID_MANUFACTURER, CONTACT_MANU_ID) VALUES ('Fabricante 2 S.A.', 10000000000002, 2, 2);
INSERT INTO MANUFACTURER (NAME_MANU, CNPJ, ADDRESS_ID_MANUFACTURER, CONTACT_MANU_ID) VALUES ('Fabricante 3 S.A.', 10000000000003, 3, 3);
INSERT INTO MANUFACTURER (NAME_MANU, CNPJ, ADDRESS_ID_MANUFACTURER, CONTACT_MANU_ID) VALUES ('Fabricante 4 S.A.', 10000000000004, 4, 4);
INSERT INTO MANUFACTURER (NAME_MANU, CNPJ, ADDRESS_ID_MANUFACTURER, CONTACT_MANU_ID) VALUES ('Fabricante 5 S.A.', 10000000000005, 5, 5);
INSERT INTO MANUFACTURER (NAME_MANU, CNPJ, ADDRESS_ID_MANUFACTURER, CONTACT_MANU_ID) VALUES ('Fabricante 6 S.A.', 10000000000006, 6, 6);
INSERT INTO MANUFACTURER (NAME_MANU, CNPJ, ADDRESS_ID_MANUFACTURER, CONTACT_MANU_ID) VALUES ('Fabricante 7 S.A.', 10000000000007, 7, 7);
INSERT INTO MANUFACTURER (NAME_MANU, CNPJ, ADDRESS_ID_MANUFACTURER, CONTACT_MANU_ID) VALUES ('Fabricante 8 S.A.', 10000000000008, 8, 8);
INSERT INTO MANUFACTURER (NAME_MANU, CNPJ, ADDRESS_ID_MANUFACTURER, CONTACT_MANU_ID) VALUES ('Fabricante 9 S.A.', 10000000000009, 9, 9);
INSERT INTO MANUFACTURER (NAME_MANU, CNPJ, ADDRESS_ID_MANUFACTURER, CONTACT_MANU_ID) VALUES ('Fabricante 10 S.A.', 10000000000010, 10, 10);
INSERT INTO MANUFACTURER (NAME_MANU, CNPJ, ADDRESS_ID_MANUFACTURER, CONTACT_MANU_ID) VALUES ('Fabricante 11 S.A.', 10000000000011, 11, 11);
INSERT INTO MANUFACTURER (NAME_MANU, CNPJ, ADDRESS_ID_MANUFACTURER, CONTACT_MANU_ID) VALUES ('Fabricante 12 S.A.', 10000000000012, 12, 12);
INSERT INTO MANUFACTURER (NAME_MANU, CNPJ, ADDRESS_ID_MANUFACTURER, CONTACT_MANU_ID) VALUES ('Fabricante 13 S.A.', 10000000000013, 13, 13);
INSERT INTO MANUFACTURER (NAME_MANU, CNPJ, ADDRESS_ID_MANUFACTURER, CONTACT_MANU_ID) VALUES ('Fabricante 14 S.A.', 10000000000014, 14, 14);
INSERT INTO MANUFACTURER (NAME_MANU, CNPJ, ADDRESS_ID_MANUFACTURER, CONTACT_MANU_ID) VALUES ('Fabricante 15 S.A.', 10000000000015, 15, 15);

------------------------------------------
-- INSERT ACTIVE_INGREDIENT
------------------------------------------
INSERT INTO ACTIVE_INGREDIENT (ACT_INGREDIENT) VALUES ('Paracetamol');
INSERT INTO ACTIVE_INGREDIENT (ACT_INGREDIENT) VALUES ('Ibuprofeno');
INSERT INTO ACTIVE_INGREDIENT (ACT_INGREDIENT) VALUES ('Amoxicilina');
INSERT INTO ACTIVE_INGREDIENT (ACT_INGREDIENT) VALUES ('Omeprazol');
INSERT INTO ACTIVE_INGREDIENT (ACT_INGREDIENT) VALUES ('Metformina');
INSERT INTO ACTIVE_INGREDIENT (ACT_INGREDIENT) VALUES ('Losartana');
INSERT INTO ACTIVE_INGREDIENT (ACT_INGREDIENT) VALUES ('AAS');
INSERT INTO ACTIVE_INGREDIENT (ACT_INGREDIENT) VALUES ('Clopidogrel');
INSERT INTO ACTIVE_INGREDIENT (ACT_INGREDIENT) VALUES ('Atorvastatina');
INSERT INTO ACTIVE_INGREDIENT (ACT_INGREDIENT) VALUES ('Diazepam');
INSERT INTO ACTIVE_INGREDIENT (ACT_INGREDIENT) VALUES ('Ciprofloxacino');
INSERT INTO ACTIVE_INGREDIENT (ACT_INGREDIENT) VALUES ('Azitromicina');
INSERT INTO ACTIVE_INGREDIENT (ACT_INGREDIENT) VALUES ('Hidroclorotiazida');
INSERT INTO ACTIVE_INGREDIENT (ACT_INGREDIENT) VALUES ('Diclofenaco');
INSERT INTO ACTIVE_INGREDIENT (ACT_INGREDIENT) VALUES ('Prednisona');

------------------------------------------
-- INSERT PHARMACEUTICAL_FORM
------------------------------------------
INSERT INTO PHARMACEUTICAL_FORM (PHARMA_FORM) VALUES ('Comprimido');
INSERT INTO PHARMACEUTICAL_FORM (PHARMA_FORM) VALUES ('Cápsula');
INSERT INTO PHARMACEUTICAL_FORM (PHARMA_FORM) VALUES ('Solução Oral');
INSERT INTO PHARMACEUTICAL_FORM (PHARMA_FORM) VALUES ('Xarope');
INSERT INTO PHARMACEUTICAL_FORM (PHARMA_FORM) VALUES ('Gotas');
INSERT INTO PHARMACEUTICAL_FORM (PHARMA_FORM) VALUES ('Injetável');
INSERT INTO PHARMACEUTICAL_FORM (PHARMA_FORM) VALUES ('Pomada');
INSERT INTO PHARMACEUTICAL_FORM (PHARMA_FORM) VALUES ('Creme');
INSERT INTO PHARMACEUTICAL_FORM (PHARMA_FORM) VALUES ('Gel');
INSERT INTO PHARMACEUTICAL_FORM (PHARMA_FORM) VALUES ('Suspensão');
INSERT INTO PHARMACEUTICAL_FORM (PHARMA_FORM) VALUES ('Supositório');
INSERT INTO PHARMACEUTICAL_FORM (PHARMA_FORM) VALUES ('Adesivo Transdérmico');
INSERT INTO PHARMACEUTICAL_FORM (PHARMA_FORM) VALUES ('Pó para Reconstituição');
INSERT INTO PHARMACEUTICAL_FORM (PHARMA_FORM) VALUES ('Spray Nasal');
INSERT INTO PHARMACEUTICAL_FORM (PHARMA_FORM) VALUES ('Colírio');

------------------------------------------
-- INSERT UNIT_MEASURE
------------------------------------------
INSERT INTO UNIT_MEASURE (UNIT_MEASURE_MEDICINE) VALUES ('mg');
INSERT INTO UNIT_MEASURE (UNIT_MEASURE_MEDICINE) VALUES ('g');
INSERT INTO UNIT_MEASURE (UNIT_MEASURE_MEDICINE) VALUES ('mcg');
INSERT INTO UNIT_MEASURE (UNIT_MEASURE_MEDICINE) VALUES ('mL');
INSERT INTO UNIT_MEASURE (UNIT_MEASURE_MEDICINE) VALUES ('L');
INSERT INTO UNIT_MEASURE (UNIT_MEASURE_MEDICINE) VALUES ('UI');
INSERT INTO UNIT_MEASURE (UNIT_MEASURE_MEDICINE) VALUES ('mg/mL');
INSERT INTO UNIT_MEASURE (UNIT_MEASURE_MEDICINE) VALUES ('g/L');
INSERT INTO UNIT_MEASURE (UNIT_MEASURE_MEDICINE) VALUES ('mEq');
INSERT INTO UNIT_MEASURE (UNIT_MEASURE_MEDICINE) VALUES ('mmol');
INSERT INTO UNIT_MEASURE (UNIT_MEASURE_MEDICINE) VALUES ('dose');
INSERT INTO UNIT_MEASURE (UNIT_MEASURE_MEDICINE) VALUES ('ampola');
INSERT INTO UNIT_MEASURE (UNIT_MEASURE_MEDICINE) VALUES ('fr');
INSERT INTO UNIT_MEASURE (UNIT_MEASURE_MEDICINE) VALUES ('cp');
INSERT INTO UNIT_MEASURE (UNIT_MEASURE_MEDICINE) VALUES ('cáps');

------------------------------------------
-- INSERT CATEGORY_MEDICINE
------------------------------------------
INSERT INTO CATEGORY_MEDICINE (CATEGORY) VALUES ('Analgésico');
INSERT INTO CATEGORY_MEDICINE (CATEGORY) VALUES ('Antibiótico');
INSERT INTO CATEGORY_MEDICINE (CATEGORY) VALUES ('Anti-inflamatório');
INSERT INTO CATEGORY_MEDICINE (CATEGORY) VALUES ('Anti-hipertensivo');
INSERT INTO CATEGORY_MEDICINE (CATEGORY) VALUES ('Hipoglicemiante');
INSERT INTO CATEGORY_MEDICINE (CATEGORY) VALUES ('Anticoagulante');
INSERT INTO CATEGORY_MEDICINE (CATEGORY) VALUES ('Estatina');
INSERT INTO CATEGORY_MEDICINE (CATEGORY) VALUES ('Ansiolítico');
INSERT INTO CATEGORY_MEDICINE (CATEGORY) VALUES ('Diurético');
INSERT INTO CATEGORY_MEDICINE (CATEGORY) VALUES ('IBP');
INSERT INTO CATEGORY_MEDICINE (CATEGORY) VALUES ('Antidepressivo');
INSERT INTO CATEGORY_MEDICINE (CATEGORY) VALUES ('Antipsicótico');
INSERT INTO CATEGORY_MEDICINE (CATEGORY) VALUES ('Antialérgico');
INSERT INTO CATEGORY_MEDICINE (CATEGORY) VALUES ('Broncodilatador');
INSERT INTO CATEGORY_MEDICINE (CATEGORY) VALUES ('Corticosteroide');

------------------------------------------
-- INSERT MEDICINES
------------------------------------------
INSERT INTO MEDICINES (NAME_MEDICATION, STATUS_MED, CATEGORY_MED_ID, UNIT_MEA_ID) VALUES ('Paracetamol 750mg', 'Ativo', 1, 1);
INSERT INTO MEDICINES (NAME_MEDICATION, STATUS_MED, CATEGORY_MED_ID, UNIT_MEA_ID) VALUES ('Ibuprofeno 400mg', 'Ativo', 3, 1);
INSERT INTO MEDICINES (NAME_MEDICATION, STATUS_MED, CATEGORY_MED_ID, UNIT_MEA_ID) VALUES ('Amoxicilina 500mg', 'Ativo', 2, 1);
INSERT INTO MEDICINES (NAME_MEDICATION, STATUS_MED, CATEGORY_MED_ID, UNIT_MEA_ID) VALUES ('Omeprazol 20mg', 'Ativo', 10, 1);
INSERT INTO MEDICINES (NAME_MEDICATION, STATUS_MED, CATEGORY_MED_ID, UNIT_MEA_ID) VALUES ('Metformina 850mg', 'Ativo', 5, 1);
INSERT INTO MEDICINES (NAME_MEDICATION, STATUS_MED, CATEGORY_MED_ID, UNIT_MEA_ID) VALUES ('Losartana 50mg', 'Ativo', 4, 1);
INSERT INTO MEDICINES (NAME_MEDICATION, STATUS_MED, CATEGORY_MED_ID, UNIT_MEA_ID) VALUES ('AAS 100mg', 'Ativo', 6, 1);
INSERT INTO MEDICINES (NAME_MEDICATION, STATUS_MED, CATEGORY_MED_ID, UNIT_MEA_ID) VALUES ('Clopidogrel 75mg', 'Ativo', 6, 1);
INSERT INTO MEDICINES (NAME_MEDICATION, STATUS_MED, CATEGORY_MED_ID, UNIT_MEA_ID) VALUES ('Atorvastatina 20mg', 'Ativo', 7, 1);
INSERT INTO MEDICINES (NAME_MEDICATION, STATUS_MED, CATEGORY_MED_ID, UNIT_MEA_ID) VALUES ('Diazepam 10mg', 'Ativo', 8, 1);
INSERT INTO MEDICINES (NAME_MEDICATION, STATUS_MED, CATEGORY_MED_ID, UNIT_MEA_ID) VALUES ('Ciprofloxacino 500mg', 'Ativo', 2, 1);
INSERT INTO MEDICINES (NAME_MEDICATION, STATUS_MED, CATEGORY_MED_ID, UNIT_MEA_ID) VALUES ('Azitromicina 500mg', 'Ativo', 2, 1);
INSERT INTO MEDICINES (NAME_MEDICATION, STATUS_MED, CATEGORY_MED_ID, UNIT_MEA_ID) VALUES ('Hidroclorotiazida 25mg', 'Ativo', 9, 1);
INSERT INTO MEDICINES (NAME_MEDICATION, STATUS_MED, CATEGORY_MED_ID, UNIT_MEA_ID) VALUES ('Diclofenaco 50mg', 'Ativo', 3, 1);
INSERT INTO MEDICINES (NAME_MEDICATION, STATUS_MED, CATEGORY_MED_ID, UNIT_MEA_ID) VALUES ('Prednisona 20mg', 'Ativo', 15, 1);

------------------------------------------
-- INSERT MEDICINE_ACTIVE_INGR
------------------------------------------
INSERT INTO MEDICINE_ACTIVE_INGR (MEDICINE_ID, ACT_INGRE_ID) VALUES (1, 1);
INSERT INTO MEDICINE_ACTIVE_INGR (MEDICINE_ID, ACT_INGRE_ID) VALUES (2, 2);
INSERT INTO MEDICINE_ACTIVE_INGR (MEDICINE_ID, ACT_INGRE_ID) VALUES (3, 3);
INSERT INTO MEDICINE_ACTIVE_INGR (MEDICINE_ID, ACT_INGRE_ID) VALUES (4, 4);
INSERT INTO MEDICINE_ACTIVE_INGR (MEDICINE_ID, ACT_INGRE_ID) VALUES (5, 5);
INSERT INTO MEDICINE_ACTIVE_INGR (MEDICINE_ID, ACT_INGRE_ID) VALUES (6, 6);
INSERT INTO MEDICINE_ACTIVE_INGR (MEDICINE_ID, ACT_INGRE_ID) VALUES (7, 7);
INSERT INTO MEDICINE_ACTIVE_INGR (MEDICINE_ID, ACT_INGRE_ID) VALUES (8, 8);
INSERT INTO MEDICINE_ACTIVE_INGR (MEDICINE_ID, ACT_INGRE_ID) VALUES (9, 9);
INSERT INTO MEDICINE_ACTIVE_INGR (MEDICINE_ID, ACT_INGRE_ID) VALUES (10, 10);
INSERT INTO MEDICINE_ACTIVE_INGR (MEDICINE_ID, ACT_INGRE_ID) VALUES (11, 11);
INSERT INTO MEDICINE_ACTIVE_INGR (MEDICINE_ID, ACT_INGRE_ID) VALUES (12, 12);
INSERT INTO MEDICINE_ACTIVE_INGR (MEDICINE_ID, ACT_INGRE_ID) VALUES (13, 13);
INSERT INTO MEDICINE_ACTIVE_INGR (MEDICINE_ID, ACT_INGRE_ID) VALUES (14, 14);
INSERT INTO MEDICINE_ACTIVE_INGR (MEDICINE_ID, ACT_INGRE_ID) VALUES (15, 15);

------------------------------------------
-- INSERT MEDICINE_PHARM_FORM
------------------------------------------
INSERT INTO MEDICINE_PHARM_FORM (MEDICINE_ID, PHARM_FORM_ID) VALUES (1, 1);
INSERT INTO MEDICINE_PHARM_FORM (MEDICINE_ID, PHARM_FORM_ID) VALUES (2, 2);
INSERT INTO MEDICINE_PHARM_FORM (MEDICINE_ID, PHARM_FORM_ID) VALUES (3, 3);
INSERT INTO MEDICINE_PHARM_FORM (MEDICINE_ID, PHARM_FORM_ID) VALUES (4, 4);
INSERT INTO MEDICINE_PHARM_FORM (MEDICINE_ID, PHARM_FORM_ID) VALUES (5, 5);
INSERT INTO MEDICINE_PHARM_FORM (MEDICINE_ID, PHARM_FORM_ID) VALUES (6, 6);
INSERT INTO MEDICINE_PHARM_FORM (MEDICINE_ID, PHARM_FORM_ID) VALUES (7, 7);
INSERT INTO MEDICINE_PHARM_FORM (MEDICINE_ID, PHARM_FORM_ID) VALUES (8, 8);
INSERT INTO MEDICINE_PHARM_FORM (MEDICINE_ID, PHARM_FORM_ID) VALUES (9, 9);
INSERT INTO MEDICINE_PHARM_FORM (MEDICINE_ID, PHARM_FORM_ID) VALUES (10, 10);
INSERT INTO MEDICINE_PHARM_FORM (MEDICINE_ID, PHARM_FORM_ID) VALUES (11, 11);
INSERT INTO MEDICINE_PHARM_FORM (MEDICINE_ID, PHARM_FORM_ID) VALUES (12, 12);
INSERT INTO MEDICINE_PHARM_FORM (MEDICINE_ID, PHARM_FORM_ID) VALUES (13, 13);
INSERT INTO MEDICINE_PHARM_FORM (MEDICINE_ID, PHARM_FORM_ID) VALUES (14, 14);
INSERT INTO MEDICINE_PHARM_FORM (MEDICINE_ID, PHARM_FORM_ID) VALUES (15, 15);

------------------------------------------
-- INSERT BATCH_MEDICINE
------------------------------------------
INSERT INTO BATCH_MEDICINE (BATCH_NUMBER, CURRENT_QUANTITY, MANUFACTURING_DATE, EXPIRATION_DATE, MANUFAC_ID) VALUES ('L0001-2025', 520, DATE '2024-01-25', DATE '2025-02-08', 1);
INSERT INTO BATCH_MEDICINE (BATCH_NUMBER, CURRENT_QUANTITY, MANUFACTURING_DATE, EXPIRATION_DATE, MANUFAC_ID) VALUES ('L0002-2024', 540, DATE '2024-02-04', DATE '2025-03-05', 2);
INSERT INTO BATCH_MEDICINE (BATCH_NUMBER, CURRENT_QUANTITY, MANUFACTURING_DATE, EXPIRATION_DATE, MANUFAC_ID) VALUES ('L0003-2025', 560, DATE '2024-02-14', DATE '2025-03-30', 3);
INSERT INTO BATCH_MEDICINE (BATCH_NUMBER, CURRENT_QUANTITY, MANUFACTURING_DATE, EXPIRATION_DATE, MANUFAC_ID) VALUES ('L0004-2024', 580, DATE '2024-02-24', DATE '2025-04-24', 4);
INSERT INTO BATCH_MEDICINE (BATCH_NUMBER, CURRENT_QUANTITY, MANUFACTURING_DATE, EXPIRATION_DATE, MANUFAC_ID) VALUES ('L0005-2025', 600, DATE '2024-03-05', DATE '2025-05-19', 5);
INSERT INTO BATCH_MEDICINE (BATCH_NUMBER, CURRENT_QUANTITY, MANUFACTURING_DATE, EXPIRATION_DATE, MANUFAC_ID) VALUES ('L0006-2024', 620, DATE '2024-03-15', DATE '2025-06-13', 6);
INSERT INTO BATCH_MEDICINE (BATCH_NUMBER, CURRENT_QUANTITY, MANUFACTURING_DATE, EXPIRATION_DATE, MANUFAC_ID) VALUES ('L0007-2025', 640, DATE '2024-03-25', DATE '2025-07-08', 7);
INSERT INTO BATCH_MEDICINE (BATCH_NUMBER, CURRENT_QUANTITY, MANUFACTURING_DATE, EXPIRATION_DATE, MANUFAC_ID) VALUES ('L0008-2024', 660, DATE '2024-04-04', DATE '2025-08-02', 8);
INSERT INTO BATCH_MEDICINE (BATCH_NUMBER, CURRENT_QUANTITY, MANUFACTURING_DATE, EXPIRATION_DATE, MANUFAC_ID) VALUES ('L0009-2025', 680, DATE '2024-04-14', DATE '2025-08-27', 9);
INSERT INTO BATCH_MEDICINE (BATCH_NUMBER, CURRENT_QUANTITY, MANUFACTURING_DATE, EXPIRATION_DATE, MANUFAC_ID) VALUES ('L0010-2024', 700, DATE '2024-04-24', DATE '2025-09-21', 10);
INSERT INTO BATCH_MEDICINE (BATCH_NUMBER, CURRENT_QUANTITY, MANUFACTURING_DATE, EXPIRATION_DATE, MANUFAC_ID) VALUES ('L0011-2025', 720, DATE '2024-05-04', DATE '2025-10-16', 11);
INSERT INTO BATCH_MEDICINE (BATCH_NUMBER, CURRENT_QUANTITY, MANUFACTURING_DATE, EXPIRATION_DATE, MANUFAC_ID) VALUES ('L0012-2024', 740, DATE '2024-05-14', DATE '2025-11-10', 12);
INSERT INTO BATCH_MEDICINE (BATCH_NUMBER, CURRENT_QUANTITY, MANUFACTURING_DATE, EXPIRATION_DATE, MANUFAC_ID) VALUES ('L0013-2025', 760, DATE '2024-05-24', DATE '2025-12-05', 13);
INSERT INTO BATCH_MEDICINE (BATCH_NUMBER, CURRENT_QUANTITY, MANUFACTURING_DATE, EXPIRATION_DATE, MANUFAC_ID) VALUES ('L0014-2024', 780, DATE '2024-06-03', DATE '2025-12-30', 14);
INSERT INTO BATCH_MEDICINE (BATCH_NUMBER, CURRENT_QUANTITY, MANUFACTURING_DATE, EXPIRATION_DATE, MANUFAC_ID) VALUES ('L0015-2025', 800, DATE '2024-06-13', DATE '2026-01-24', 15);

------------------------------------------
-- INSERT MOVEMENT_TYPE
------------------------------------------
INSERT INTO MOVEMENT_TYPE (TYPE_NAME) VALUES ('Entrada Nota Fiscal');
INSERT INTO MOVEMENT_TYPE (TYPE_NAME) VALUES ('Ajuste Positivo');
INSERT INTO MOVEMENT_TYPE (TYPE_NAME) VALUES ('Ajuste Negativo');
INSERT INTO MOVEMENT_TYPE (TYPE_NAME) VALUES ('Transferência Entrada');
INSERT INTO MOVEMENT_TYPE (TYPE_NAME) VALUES ('Transferência Saída');
INSERT INTO MOVEMENT_TYPE (TYPE_NAME) VALUES ('Dispensação');
INSERT INTO MOVEMENT_TYPE (TYPE_NAME) VALUES ('Inventário');
INSERT INTO MOVEMENT_TYPE (TYPE_NAME) VALUES ('Devolução');
INSERT INTO MOVEMENT_TYPE (TYPE_NAME) VALUES ('Perda');
INSERT INTO MOVEMENT_TYPE (TYPE_NAME) VALUES ('Vencimento');
INSERT INTO MOVEMENT_TYPE (TYPE_NAME) VALUES ('Doação');
INSERT INTO MOVEMENT_TYPE (TYPE_NAME) VALUES ('Recebimento Emergencial');
INSERT INTO MOVEMENT_TYPE (TYPE_NAME) VALUES ('Quarentena');
INSERT INTO MOVEMENT_TYPE (TYPE_NAME) VALUES ('Bloqueio');
INSERT INTO MOVEMENT_TYPE (TYPE_NAME) VALUES ('Desbloqueio');

---------------------
-- INSERT STOCK
---------------------
INSERT INTO STOCK (QUANTITY, BATCH_ID, MEDICINE_ID, LOCATION_ID_STOCK) VALUES (105, 1, 1, 1);
INSERT INTO STOCK (QUANTITY, BATCH_ID, MEDICINE_ID, LOCATION_ID_STOCK) VALUES (110, 2, 2, 2);
INSERT INTO STOCK (QUANTITY, BATCH_ID, MEDICINE_ID, LOCATION_ID_STOCK) VALUES (115, 3, 3, 3);
INSERT INTO STOCK (QUANTITY, BATCH_ID, MEDICINE_ID, LOCATION_ID_STOCK) VALUES (120, 4, 4, 4);
INSERT INTO STOCK (QUANTITY, BATCH_ID, MEDICINE_ID, LOCATION_ID_STOCK) VALUES (125, 5, 5, 5);
INSERT INTO STOCK (QUANTITY, BATCH_ID, MEDICINE_ID, LOCATION_ID_STOCK) VALUES (130, 6, 6, 6);
INSERT INTO STOCK (QUANTITY, BATCH_ID, MEDICINE_ID, LOCATION_ID_STOCK) VALUES (135, 7, 7, 7);
INSERT INTO STOCK (QUANTITY, BATCH_ID, MEDICINE_ID, LOCATION_ID_STOCK) VALUES (140, 8, 8, 8);
INSERT INTO STOCK (QUANTITY, BATCH_ID, MEDICINE_ID, LOCATION_ID_STOCK) VALUES (145, 9, 9, 9);
INSERT INTO STOCK (QUANTITY, BATCH_ID, MEDICINE_ID, LOCATION_ID_STOCK) VALUES (150, 10, 10, 10);
INSERT INTO STOCK (QUANTITY, BATCH_ID, MEDICINE_ID, LOCATION_ID_STOCK) VALUES (155, 11, 11, 11);
INSERT INTO STOCK (QUANTITY, BATCH_ID, MEDICINE_ID, LOCATION_ID_STOCK) VALUES (160, 12, 12, 12);
INSERT INTO STOCK (QUANTITY, BATCH_ID, MEDICINE_ID, LOCATION_ID_STOCK) VALUES (165, 13, 13, 13);
INSERT INTO STOCK (QUANTITY, BATCH_ID, MEDICINE_ID, LOCATION_ID_STOCK) VALUES (170, 14, 14, 14);
INSERT INTO STOCK (QUANTITY, BATCH_ID, MEDICINE_ID, LOCATION_ID_STOCK) VALUES (175, 15, 15, 15);

------------------------------------------
-- INSERT MEDICINE_DISPENSE
------------------------------------------
INSERT INTO MEDICINE_DISPENSE (DATE_DISPENSATION, QUANTITY_DISPENSED, DESTINATION, USER_ID) VALUES (DATE '2025-09-03', 6, 'Unidade 1', 1);
INSERT INTO MEDICINE_DISPENSE (DATE_DISPENSATION, QUANTITY_DISPENSED, DESTINATION, USER_ID) VALUES (DATE '2025-09-05', 7, 'Unidade 2', 2);
INSERT INTO MEDICINE_DISPENSE (DATE_DISPENSATION, QUANTITY_DISPENSED, DESTINATION, OBSERVATION, USER_ID) VALUES (DATE '2025-09-07', 8, 'Unidade 3', 'Uso hospitalar', 3);
INSERT INTO MEDICINE_DISPENSE (DATE_DISPENSATION, QUANTITY_DISPENSED, DESTINATION, USER_ID) VALUES (DATE '2025-09-09', 9, 'Unidade 4', 4);
INSERT INTO MEDICINE_DISPENSE (DATE_DISPENSATION, QUANTITY_DISPENSED, DESTINATION, USER_ID) VALUES (DATE '2025-09-11', 10, 'Unidade 5', 5);
INSERT INTO MEDICINE_DISPENSE (DATE_DISPENSATION, QUANTITY_DISPENSED, DESTINATION, OBSERVATION, USER_ID) VALUES (DATE '2025-09-13', 11, 'Unidade 1', 'Uso hospitalar', 6);
INSERT INTO MEDICINE_DISPENSE (DATE_DISPENSATION, QUANTITY_DISPENSED, DESTINATION, USER_ID) VALUES (DATE '2025-09-15', 5, 'Unidade 2', 7);
INSERT INTO MEDICINE_DISPENSE (DATE_DISPENSATION, QUANTITY_DISPENSED, DESTINATION, USER_ID) VALUES (DATE '2025-09-17', 6, 'Unidade 3', 8);
INSERT INTO MEDICINE_DISPENSE (DATE_DISPENSATION, QUANTITY_DISPENSED, DESTINATION, OBSERVATION, USER_ID) VALUES (DATE '2025-09-19', 7, 'Unidade 4', 'Uso hospitalar', 9);
INSERT INTO MEDICINE_DISPENSE (DATE_DISPENSATION, QUANTITY_DISPENSED, DESTINATION, USER_ID) VALUES (DATE '2025-09-21', 8, 'Unidade 5', 10);
INSERT INTO MEDICINE_DISPENSE (DATE_DISPENSATION, QUANTITY_DISPENSED, DESTINATION, USER_ID) VALUES (DATE '2025-09-23', 9, 'Unidade 1', 11);
INSERT INTO MEDICINE_DISPENSE (DATE_DISPENSATION, QUANTITY_DISPENSED, DESTINATION, OBSERVATION, USER_ID) VALUES (DATE '2025-09-25', 10, 'Unidade 2', 'Uso hospitalar', 12);
INSERT INTO MEDICINE_DISPENSE (DATE_DISPENSATION, QUANTITY_DISPENSED, DESTINATION, USER_ID) VALUES (DATE '2025-09-27', 11, 'Unidade 3', 13);
INSERT INTO MEDICINE_DISPENSE (DATE_DISPENSATION, QUANTITY_DISPENSED, DESTINATION, USER_ID) VALUES (DATE '2025-09-29', 5, 'Unidade 4', 14);
INSERT INTO MEDICINE_DISPENSE (DATE_DISPENSATION, QUANTITY_DISPENSED, DESTINATION, OBSERVATION, USER_ID) VALUES (DATE '2025-10-01', 6, 'Unidade 5', 'Uso hospitalar', 15);

------------------------------------------
-- INSERT STOCK_MOVEMENT
------------------------------------------
INSERT INTO STOCK_MOVEMENT (QUANTITY_DISPENSED, DATE_MOVIMENT, MOVEMENT_TYPE_ID, STOCK_ID, DISPENSATION_ID, USER_ID) VALUES (3, DATE '2025-09-06', 1, 1, 1, 1);
INSERT INTO STOCK_MOVEMENT (QUANTITY_DISPENSED, DATE_MOVIMENT, MOVEMENT_TYPE_ID, STOCK_ID, DISPENSATION_ID, USER_ID) VALUES (4, DATE '2025-09-07', 2, 2, 2, 2);
INSERT INTO STOCK_MOVEMENT (QUANTITY_DISPENSED, DATE_MOVIMENT, MOVEMENT_TYPE_ID, STOCK_ID, DISPENSATION_ID, USER_ID) VALUES (5, DATE '2025-09-08', 3, 3, 3, 3);
INSERT INTO STOCK_MOVEMENT (QUANTITY_DISPENSED, DATE_MOVIMENT, MOVEMENT_TYPE_ID, STOCK_ID, DISPENSATION_ID, USER_ID) VALUES (6, DATE '2025-09-09', 4, 4, 4, 4);
INSERT INTO STOCK_MOVEMENT (QUANTITY_DISPENSED, DATE_MOVIMENT, MOVEMENT_TYPE_ID, STOCK_ID, DISPENSATION_ID, USER_ID) VALUES (7, DATE '2025-09-10', 5, 5, 5, 5);
INSERT INTO STOCK_MOVEMENT (QUANTITY_DISPENSED, DATE_MOVIMENT, MOVEMENT_TYPE_ID, STOCK_ID, DISPENSATION_ID, USER_ID) VALUES (2, DATE '2025-09-11', 6, 6, 6, 6);
INSERT INTO STOCK_MOVEMENT (QUANTITY_DISPENSED, DATE_MOVIMENT, MOVEMENT_TYPE_ID, STOCK_ID, DISPENSATION_ID, USER_ID) VALUES (3, DATE '2025-09-12', 7, 7, 7, 7);
INSERT INTO STOCK_MOVEMENT (QUANTITY_DISPENSED, DATE_MOVIMENT, MOVEMENT_TYPE_ID, STOCK_ID, DISPENSATION_ID, USER_ID) VALUES (4, DATE '2025-09-13', 8, 8, 8, 8);
INSERT INTO STOCK_MOVEMENT (QUANTITY_DISPENSED, DATE_MOVIMENT, MOVEMENT_TYPE_ID, STOCK_ID, DISPENSATION_ID, USER_ID) VALUES (5, DATE '2025-09-14', 9, 9, 9, 9);
INSERT INTO STOCK_MOVEMENT (QUANTITY_DISPENSED, DATE_MOVIMENT, MOVEMENT_TYPE_ID, STOCK_ID, DISPENSATION_ID, USER_ID) VALUES (6, DATE '2025-09-15', 10, 10, 10, 10);
INSERT INTO STOCK_MOVEMENT (QUANTITY_DISPENSED, DATE_MOVIMENT, MOVEMENT_TYPE_ID, STOCK_ID, DISPENSATION_ID, USER_ID) VALUES (7, DATE '2025-09-16', 11, 11, 11, 11);
INSERT INTO STOCK_MOVEMENT (QUANTITY_DISPENSED, DATE_MOVIMENT, MOVEMENT_TYPE_ID, STOCK_ID, DISPENSATION_ID, USER_ID) VALUES (2, DATE '2025-09-17', 12, 12, 12, 12);
INSERT INTO STOCK_MOVEMENT (QUANTITY_DISPENSED, DATE_MOVIMENT, MOVEMENT_TYPE_ID, STOCK_ID, DISPENSATION_ID, USER_ID) VALUES (3, DATE '2025-09-18', 13, 13, 13, 13);
INSERT INTO STOCK_MOVEMENT (QUANTITY_DISPENSED, DATE_MOVIMENT, MOVEMENT_TYPE_ID, STOCK_ID, DISPENSATION_ID, USER_ID) VALUES (4, DATE '2025-09-19', 14, 14, 14, 14);
INSERT INTO STOCK_MOVEMENT (QUANTITY_DISPENSED, DATE_MOVIMENT, MOVEMENT_TYPE_ID, STOCK_ID, DISPENSATION_ID, USER_ID) VALUES (5, DATE '2025-09-20', 15, 15, 15, 15);

COMMIT;


--------------------------------------
-- BLOCO ANÔNIMOS
--------------------------------------

SET SERVEROUTPUT ON;
------------------------------------------------------------------------------------------------------------------
-- LEFT JOIN
-- listar todos os medicamentos, somando a quantidade
------------------------------------------------------------------------------------------------------------------
DECLARE
  CURSOR c_left IS
    SELECT
      m.medicine_id,
      m.name_medication,
      NVL(SUM(s.quantity), 0) AS total_qty
    FROM medicines m
      LEFT JOIN stock s ON s.medicine_id = m.medicine_id
    GROUP BY
      m.medicine_id, m.name_medication
    ORDER BY
      total_qty ASC, m.name_medication;
BEGIN
  DBMS_OUTPUT.PUT_LINE(RPAD('MED_ID',6)||'  '||
                       RPAD('MEDICAMENTO',30)||'  '||
                       LPAD('QTD_ESTOQUE',12));
  DBMS_OUTPUT.PUT_LINE(RPAD('-',54,'-'));

  FOR r IN c_left LOOP
    DBMS_OUTPUT.PUT_LINE(
      LPAD(r.medicine_id,6)||'  '||
      RPAD(r.name_medication,30)||'  '||
      LPAD(r.total_qty,12)
    );
  END LOOP;
END;
/

------------------------------------------------------------------------------------------------------------------
-- RIGHT JOIN 
-- listar todos os tipos de movimento, com quantidade de movimentos e soma das quantidades
------------------------------------------------------------------------------------------------------------------

DECLARE
  CURSOR c_right IS
    SELECT
      mt.movement_type_id,
      mt.type_name,
      COUNT(sm.stock_movement_id) AS qtd_mov,
      NVL(SUM(sm.quantity_dispensed), 0) AS total_qty_moved
    FROM stock_movement sm
      RIGHT JOIN movement_type mt
        ON mt.movement_type_id = sm.movement_type_id
    GROUP BY
      mt.movement_type_id, mt.type_name
    ORDER BY
      mt.type_name;
BEGIN
  DBMS_OUTPUT.PUT_LINE(RPAD('TYPE_ID',7)||'  '||
                       RPAD('TIPO_MOVIMENTO',26)||'  '||
                       LPAD('QT_MOV',6)||'  '||
                       LPAD('QTD_SOMADA',12));
  DBMS_OUTPUT.PUT_LINE(RPAD('-',60,'-'));

  FOR r IN c_right LOOP
    DBMS_OUTPUT.PUT_LINE(
      LPAD(r.movement_type_id,7)||'  '||
      RPAD(r.type_name,26)||'  '||
      LPAD(r.qtd_mov,6)||'  '||
      LPAD(r.total_qty_moved,12)
    );
  END LOOP;
END;
/

----------------------------------------------------------------------------
-- INNER JOIN
-- estoque total por Local de Estoque e Categoria do medicamento
----------------------------------------------------------------------------

DECLARE
  CURSOR c_inner IS
    SELECT
      ls.location_id_stock,
      ls.name_location,
      cm.category,
      SUM(s.quantity) AS total_qty
    FROM stock s
      INNER JOIN location_stock ls   ON ls.location_id_stock = s.location_id_stock
      INNER JOIN medicines m         ON m.medicine_id        = s.medicine_id
      INNER JOIN category_medicine cm ON cm.category_med_id   = m.category_med_id
    GROUP BY
      ls.location_id_stock, ls.name_location, cm.category
    ORDER BY
      ls.name_location, cm.category;
BEGIN
  DBMS_OUTPUT.PUT_LINE(RPAD('LOC_ID',6)||'  '||
                       RPAD('LOCAL',22)||'  '||
                       RPAD('CATEGORIA',22)||'  '||
                       LPAD('QTD',6));
  DBMS_OUTPUT.PUT_LINE(RPAD('-',63,'-'));

  FOR r IN c_inner LOOP
    DBMS_OUTPUT.PUT_LINE(
      LPAD(r.location_id_stock,6)||'  '||
      RPAD(r.name_location,22)||'  '||
      RPAD(r.category,22)||'  '||
      LPAD(r.total_qty,6)
    );
  END LOOP;
END;
/

----------------------------------------------------------------------------
-- ajuste de estoque por medicamento + lote + local
----------------------------------------------------------------------------

DECLARE

  v_medicine_id        STOCK.MEDICINE_ID%TYPE       := 2;
  v_batch_id           STOCK.BATCH_ID%TYPE          := 2;
  v_location_id_stock  STOCK.LOCATION_ID_STOCK%TYPE := 2;
  v_delta              NUMBER := -7; 
  v_exists   NUMBER;
  v_current  STOCK.QUANTITY%TYPE;
  v_new      STOCK.QUANTITY%TYPE;
BEGIN
  SELECT COUNT(*)
    INTO v_exists
    FROM STOCK
   WHERE MEDICINE_ID = v_medicine_id
     AND BATCH_ID = v_batch_id
     AND LOCATION_ID_STOCK = v_location_id_stock;

  IF v_exists = 0 THEN
    DBMS_OUTPUT.PUT_LINE('Estoque não encontrado para os parâmetros informados.');
    RETURN;
  END IF;

  SELECT QUANTITY
    INTO v_current
    FROM STOCK
   WHERE MEDICINE_ID = v_medicine_id
     AND BATCH_ID = v_batch_id
     AND LOCATION_ID_STOCK = v_location_id_stock;

  v_new := v_current + v_delta;

  IF v_new < 0 THEN
    DBMS_OUTPUT.PUT_LINE('Operação cancelada: quantidade ficaria negativa (atual='||v_current||', delta='||v_delta||').');
    ROLLBACK;
  ELSE
    UPDATE STOCK
       SET QUANTITY = v_new
     WHERE MEDICINE_ID = v_medicine_id
       AND BATCH_ID = v_batch_id
       AND LOCATION_ID_STOCK = v_location_id_stock;

    DBMS_OUTPUT.PUT_LINE('UPDATE ok. Linhas afetadas: '||SQL%ROWCOUNT||
                         ' | Quantidade: '||v_current||' -> '||v_new);
    COMMIT;
  END IF;
END;
/


----------------------------------------------------------------------------
-- remove vínculo de forma farmacêutica de um medicamento
----------------------------------------------------------------------------

DECLARE
  v_medicine_id   MEDICINE_PHARM_FORM.MEDICINE_ID%TYPE := 2;
  v_pharm_form_id MEDICINE_PHARM_FORM.PHARM_FORM_ID%TYPE := 2;

  v_exists_pair NUMBER;
  v_med_exists  NUMBER;
  v_pf_exists   NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_med_exists FROM MEDICINES WHERE MEDICINE_ID = v_medicine_id;
  SELECT COUNT(*) INTO v_pf_exists  FROM PHARMACEUTICAL_FORM WHERE PHARM_FORM_ID = v_pharm_form_id;

  IF v_med_exists = 0 THEN
    DBMS_OUTPUT.PUT_LINE('Medicamento não existe: ID='||v_medicine_id);
    RETURN;
  END IF;

  IF v_pf_exists = 0 THEN
    DBMS_OUTPUT.PUT_LINE('Forma farmacêutica não existe: ID='||v_pharm_form_id);
    RETURN;
  END IF;

  SELECT COUNT(*)
    INTO v_exists_pair
    FROM MEDICINE_PHARM_FORM
   WHERE MEDICINE_ID = v_medicine_id
     AND PHARM_FORM_ID = v_pharm_form_id;

  IF v_exists_pair = 0 THEN
    DBMS_OUTPUT.PUT_LINE('Nenhum vínculo para remover (MEDICINE_ID='||v_medicine_id||
                         ', PHARM_FORM_ID='||v_pharm_form_id||').');
    RETURN;
  END IF;

  DELETE FROM MEDICINE_PHARM_FORM
   WHERE MEDICINE_ID = v_medicine_id
     AND PHARM_FORM_ID = v_pharm_form_id;

  DBMS_OUTPUT.PUT_LINE('DELETE ok. Linhas afetadas: '||SQL%ROWCOUNT||
                       ' | Removido vínculo MEDICINE_ID='||v_medicine_id||
                       ' e PHARM_FORM_ID='||v_pharm_form_id||'.');
  COMMIT;
END;
/
